.PHONY: all clean cleanall

all:
	$(MAKE) -C tinyPTC
#	$(MAKE) -C picoPTC
clean:
	$(MAKE) -C tinyPTC clean
#	$(MAKE) -C picoPTC clean
cleanall:	
	$(MAKE) -C tinyPTC cleanall
#       $(MAKE) -C picoPTC cleanall

